name: EscapeQuad Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build_and_Test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get -y install build-essential

    - name: Download and install criterion
      run: sudo apt-get install libcriterion-dev

    - name: make
      run: cc main.c -lcriterion
  
    - name: Run Test Cases
      run: ./a.out -S --verbose=0 --timeout 30
